version: '3'
services:
  php:
    container_name: phpMNP
    build: .
    volumes:
      - ./project:/var/www/html/
    ports:
      - 8808:80
  ssh:
    container_name: sshMNP
    image: rastasheep/ubuntu-sshd
    ports:
      - 2222:22
